---

  CONTRIBUTOR_EMAIL:
    transport:
      debug: false
      logger: true

  CONVERT_FORMAT_COMMAND: "pandoc"

  DEFAULT_DB_ENDPOINT: https://dynamodb.eu-west-1.amazonaws.com

  DB:
    BACKUP:
      bucket:
        directory: production
    ssl: true

  NODE_ENV: production

  REDSHIFT:
    bucket:
      directory: redshift

  SALESFORCE:
    ENVIRONMENT: production
